-- 1. List each pair of actors that have worked together.

-- AS I UNDERSTAND REPEAT THE SAME WITH CTE
SELECT *
FROM SAKILA.FILM_ACTOR
ORDER BY 2,1;


SELECT FA1.ACTOR_ID AS ACTOR_ID_FIRST, FA2.ACTOR_ID AS ACTOR_ID_SECOND, FA1.FILM_ID
FROM SAKILA.FILM_ACTOR FA1
INNER JOIN SAKILA.FILM_ACTOR FA2 
ON FA1.FILM_ID = FA2.FILM_ID
AND FA1.ACTOR_ID <> FA2.ACTOR_ID;


WITH CTE_ACTOR_SELF_JOIN AS (
	SELECT F1.ACTOR_ID AS ACTOR_ID_FIRST, F2.ACTOR_ID AS ACTOR_ID_SECOND, F1.FILM_ID
    FROM SAKILA.FILM_ACTOR F1
    INNER JOIN SAKILA.FILM_ACTOR F2
    ON F1.FILM_ID = F2.FILM_ID
    AND F1.ACTOR_ID <> F2.ACTOR_ID
)
SELECT * 
FROM CTE_ACTOR_SELF_JOIN;


-- 2. For each film, list actor that has acted in more films.

SELECT *
FROM SAKILA.FILM_ACTOR
ORDER BY 2,1;

SELECT ACTOR_ID, COUNT(FILM_ID) AS FILMS_ACTED
FROM SAKILA.FILM_ACTOR
GROUP BY ACTOR_ID;

WITH CTE_ACTOR_COUNT AS (
	SELECT ACTOR_ID, COUNT(FILM_ID) AS FILMS_ACTED
	FROM SAKILA.FILM_ACTOR
	GROUP BY ACTOR_ID
)
SELECT CTE.ACTOR_ID, CTE.FILMS_ACTED, FA.FILM_ID
FROM CTE_ACTOR_COUNT CTE
LEFT JOIN SAKILA.FILM_ACTOR FA
ON CTE.ACTOR_ID = FA.ACTOR_ID
ORDER BY 3;





-- ES GAMODIS CHEMI PASUXI  -- ESEC SIGIJE



SELECT FIRST_NAME, LAST_NAME 
FROM SAKILA.ACTOR
WHERE ACTOR_ID IN (
	WITH CTE_ACTOR_WITH_MOST_FILMS AS (
WITH CTE_ACTOR_COUNT AS (
	SELECT ACTOR_ID, COUNT(FILM_ID) AS FILMS_ACTED
	FROM SAKILA.FILM_ACTOR
	GROUP BY ACTOR_ID
)
SELECT CTE.ACTOR_ID, CTE.FILMS_ACTED, FA.FILM_ID
FROM CTE_ACTOR_COUNT CTE
LEFT JOIN SAKILA.FILM_ACTOR FA
ON CTE.ACTOR_ID = FA.ACTOR_ID
ORDER BY 3
)
SELECT ACTOR_ID
FROM CTE_ACTOR_WITH_MOST_FILMS
WHERE (FILM_ID, FILMS_ACTED) IN (
    SELECT FILM_ID, MAX(FILMS_ACTED) 
    FROM CTE_ACTOR_WITH_MOST_FILMS
    GROUP BY FILM_ID
)
)
;

-- ES GAMODIS CHEMI PASUXI


WITH CTE_ACTOR_WITH_MOST_FILMS AS (
WITH CTE_ACTOR_COUNT AS (
	SELECT ACTOR_ID, COUNT(FILM_ID) AS FILMS_ACTED
	FROM SAKILA.FILM_ACTOR
	GROUP BY ACTOR_ID
)
SELECT CTE.ACTOR_ID, CTE.FILMS_ACTED, FA.FILM_ID
FROM CTE_ACTOR_COUNT CTE
LEFT JOIN SAKILA.FILM_ACTOR FA
ON CTE.ACTOR_ID = FA.ACTOR_ID
ORDER BY 3
)
SELECT ACTOR_ID
FROM CTE_ACTOR_WITH_MOST_FILMS
WHERE (FILM_ID, FILMS_ACTED) IN (
    SELECT FILM_ID, MAX(FILMS_ACTED) 
    FROM CTE_ACTOR_WITH_MOST_FILMS
    GROUP BY FILM_ID
);







WITH CTE_ACTOR_COUNT AS (
	SELECT ACTOR_ID, COUNT(FILM_ID) AS FILMS_ACTED
	FROM SAKILA.FILM_ACTOR
	GROUP BY ACTOR_ID
)
SELECT CTE.ACTOR_ID, CTE.FILMS_ACTED, FA.FILM_ID
FROM CTE_ACTOR_COUNT CTE
LEFT JOIN SAKILA.FILM_ACTOR FA
ON CTE.ACTOR_ID = FA.ACTOR_ID
ORDER BY 3;


SELECT ACTOR_ID
FROM SAKILA.ACTORS_FILMS
WHERE FILM_ID IN (
	SELECT FILM_ID, MAX(FILMS_ACTED)
	FROM SAKILA.ACTORS_FILMS
	GROUP BY 1
)
;


SELECT FILM_ID, MAX(FILMS_ACTED)
FROM SAKILA.ACTORS_FILMS
GROUP BY 1;